---

- type: replace
  path: /instance_groups/name=graylog/jobs/name=graylog/properties/graylog?
  value:
    root_email: ((graylog-root-email))
    root_username: ((graylog-root-username))
    root_password_sha2: ((graylog-root-password-sha2))
