azs:
- name: z1
  cloud_properties:
    availability_zone: ## FIX ME
- name: z2
  cloud_properties:
    availability_zone: ## FIX ME
- name: z3
  cloud_properties:
    availability_zone: ## FIX ME

vm_types:
- name: default
  cloud_properties:
    {"instance_type": "t2.micro", "ephemeral_disk": {"type": "gp2", "size": 10240}}

disk_types:
- name: default
  disk_size: 3000
  cloud_properties:
    {"type": "gp2"}

resource_pools:
  - name: default
    stemcell:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest

## FIX UP THE IP RANGES
networks:
- name: compilation_a
  type: manual
  subnets:
  - range: 10.148.0.0/24
    gateway: 10.148.0.1
    azs: [z1]
    dns: [8.8.8.8]
    reserved: [10.148.0.1/30]
    static: [10.148.0.4 - 10.148.0.99]
    cloud_properties:
      subnet: subnet- ## FIX ME
- name: mongodb_a
  type: manual
  subnets:
  - range: 10.148.1.0/24
    gateway: 10.148.1.1
    azs: [z1]
    dns: [8.8.8.8]
    reserved: [10.148.1.1/30]
    static: [10.148.1.4 - 10.148.1.99]
    cloud_properties:
      subnet: subnet- ## FIX ME
- name: elasticsearch_a
  type: manual
  subnets:
  - range: 10.148.2.0/24
    gateway: 10.148.2.1
    azs: [z1]
    dns: [8.8.8.8]
    reserved: [10.148.2.1/30]
    static: [10.148.2.4 - 10.148.2.99]
    cloud_properties:
      subnet: subnet- ## FIX ME
- name: graylog_a
  type: manual
  subnets:
  - range: 10.148.3.0/24
    gateway: 10.148.3.1
    azs: [z1]
    dns: [8.8.8.8]
    reserved: [10.148.3.1/30]
    static: [10.148.3.4 - 10.148.3.99]
    cloud_properties:
      subnet: subnet- ## FIX ME
- name: vip
  type: vip

compilation:
  workers: 2
  reuse_compilation_vms: True
  az: [z1]
  vm_type: default
  network: compilation_a

