azs:
- name: z1

networks:
- name: default
  type: manual
  subnets:
    - azs: [z1]
      range: 10.244.0.0/24
      reserved: [10.244.0.1]
      static: [10.244.0.2 - 10.244.0.99]

- name: graylog_a
  type: manual
  subnets:
    - range: 10.244.1.0/24
      azs: [z1]
      gateway: 10.244.1.1
      static: [10.244.1.2 - 10.244.1.99]
- name: elasticsearch_a
  type: manual
  subnets:
    - range: 10.244.2.0/24
      azs: [z1]
      gateway: 10.244.2.1
      static: [10.244.2.2 - 10.244.2.99]
- name: mongodb_a
  type: manual
  subnets:
    - range: 10.244.3.0/24
      azs: [z1]
      gateway: 10.244.3.1
      static: [10.244.3.2 - 10.244.3.99]

resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest

compilation:
  workers: 1
  network: default
  cloud_properties: {}

disk_types:
- name: default
  disk_size: 1024

